spring.application.name=LawMIS

server.port=8081
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://localhost:5432/lawDB
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
datasource.name=lawDB

# Max file size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Backup and restore configuration for SERVER (Linux)
backup.path=/opt/lawmis/backups/
pgdump.address=/usr/bin/pg_dump
attachments.path=/opt/lawmis/attachments/

# JPA properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false  # Set to false in production
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false  # Disable in production for security
spring.servlet.multipart.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springdoc=INFO
logging.level.org.springframework.web=INFO

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=idreesdaudzai2000@gmail.com
spring.mail.password=avox vnib gjkm hyxi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true