spring.application.name=LawMIS

server.port=8081
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://localhost:5432/lawDB
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
datasource.name=lawDB

# Upload
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.enabled=true

# Backup (IMPORTANT)
backup.path=/opt/lawmis/backups/
pgdump.address=${PG_DUMP_PATH:/usr/bin/pg_dump}
pgrestore.address=${PG_RESTORE_PATH:/usr/bin/pg_restore}
file.storage.base-path=/opt/lawmis/attachments
attachments.path=/opt/lawmis/attachments/

# Attachments (FIXED)
attachments.path=/opt/lawmis/attachments/
file.storage.base-path=/opt/lawmis/attachments
file.storage.laws-subdir=laws
file.storage.registry-subdir=registry
file.storage.profile-subdir=profileImages

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.level.org.springdoc=INFO
logging.level.org.springframework.web=INFO

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zalmaihabibi3@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD:CHANGE_THIS_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
